project:
  type: website
  output-dir: _site
  render: [index.qmd]
  pre-render: _extensions/Afonenko-Course-Tools/course-site/entrypoints/pre.ts
  post-render: _extensions/Afonenko-Course-Tools/course-site/entrypoints/post.ts
website:
  title: Материалы курса
format:
  html:
    theme: cosmo
lang: ru
reference-catalog:
  namespace: site
filters: [reference-catalog]
subprojects: [book, lectures, practice]
profile:
  default: full
