project:
  type: website
  output-dir: _site
  render: [index.qmd]
  pre-render: _extensions/course-site/entrypoints/pre.ts
  post-render: _extensions/course-site/entrypoints/post.ts
website:
  title: Материалы курса
format:
  html:
    theme: cosmo
lang: ru
reference-catalog:
  namespace: site
filters: [reference-catalog]
course-site:
  projects:
    - id: book
      path: book
      format: html
      mount: book
    - id: lectures
      path: lectures
      format: revealjs
      mount: lectures
    - id: practice
      path: practice
      format: revealjs
      mount: practice
