project:
  type: website
  output-dir: _site
  render: []
  pre-render: _extensions/project-publish/entrypoints/pre.ts
  post-render: _extensions/project-publish/entrypoints/post.ts
website:
  title: Материалы курса
format:
  html:
    theme: cosmo
lang: ru
reference-catalog:
  exports:
    book: "*"
    lectures: "*"
    practice: "*"
project-publish:
  home: book
  integrations: [_extensions/reference-catalog/entrypoints/publication.ts]
  projects:
    book:
      path: book
      format: html
    lectures:
      path: lectures
      format: revealjs
    practice:
      path: practice
      format: revealjs
