project:
  type: default
  post-render:
    - _extensions/reference-catalog/entrypoints/post.ts
    - ../_extensions/course-site/entrypoints/collect.ts
  output-dir: _output
  render:
    - "**/*.qmd"
format:
  revealjs:
    theme: simple
    hash: true
lang: ru
number-sections: false

filters: [reference-catalog]
reference-catalog:
  namespace: practice
profile:
  default: full
