project:
  type: book
  post-render:
    - _extensions/reference-catalog/entrypoints/post.ts
    - ../_extensions/course-site/entrypoints/collect.ts
  output-dir: _book
book:
  title: Программирование
  chapters:
    - index.qmd
    - topics/objects.qmd
  appendices:
    - appendix.qmd
format:
  html:
    theme: cosmo
lang: ru
crossref:
  fig-labels: roman
  custom:
    - key: vid
      kind: float
      reference-prefix: Видео

filters: [reference-catalog]
reference-catalog:
  namespace: book
  exports:
    book: "*"
