fail-if-warnings: true
project:
  type: book
  post-render:
    - _extensions/Afonenko-Course-Tools/reference-catalog/entrypoints/post.ts
    - ../_extensions/Afonenko-Course-Tools/course-site/entrypoints/collect.ts
  output-dir: _book
book:
  repo-url: https://github.com/Afonenko-Course-Tools/quarto-reference-catalog
  repo-branch: v3.0.0
  repo-subdir: examples/course/book
  repo-actions: [source]
  title: Программирование
  chapters:
    - index.qmd
    - topics/objects.qmd
  appendices:
    - appendix.qmd
format:
  html:
    theme: cosmo
lang: ru
crossref:
  fig-labels: roman
  custom:
    - key: vid
      kind: float
      reference-prefix: Видео

filters: [reference-catalog]
reference-catalog:
  namespace: book
profile:
  default: full
