fail-if-warnings: true
project:
  type: website
  output-dir: _site
  render: [index.qmd]
  post-render: _extensions/Afonenko-Course-Tools/reference-catalog/entrypoints/post.ts
profile:
  default: full
website:
  title: Внешний адресный каталог
  repo-url: https://github.com/Afonenko-Course-Tools/quarto-reference-catalog
  repo-branch: v3.0.0
  repo-subdir: examples/external
  repo-actions: [source]
lang: ru
format: html
filters: [reference-catalog]
reference-catalog:
  namespace: external-demo
  imports:
    docs:
      source: external-address-catalog.json
      namespace: quarto-docs
      base-url: https://quarto.org/
      style: external
