version: '3'
tasks:
  install:
    cmds:
      - quarto add Afonenko-Course-Tools/quarto-reference-catalog@v2.2.1 --no-prompt
  render:
    cmds:
      - quarto render
      - quarto run build-info.ts
